digidem/comapeo-schema

examples/schema_test.js
index.js
proto/field/v1.proto
schema/common/v1.json
schema/coreOwnership/v1.json
schema/device/v1.json
schema/observation/v5.json
schema/role/v1.json
scripts/generate.js
test/docs.js

To have consistency with `schemaVersion` I refactored `type` to `schemaType`. This also solves the issue of the `Field` v1 schema that uses `type` for smth completely different. 
This closes issue #37

feat: refactor type to schemaType

---

index.js
package.json
scripts/generate.js

better exporting of types

---

.github/workflows/release.yml

npm build is triggered anyway by the `prepare` step.
Needing to create this as a PR because the workflow runs when I close this PR.

chore: remove build-command from release action

---

.github/workflows/release.yml

This reverts commit a355c7a7a1b75bd8cfad68e1fb51efed41c88ce6.
I removed it because the build script was running twice, however this turned out to be due to using the `prepare` npm script, but this has been switched to `prepublishOnly` in 40dc057, so we need the build script here again.

Revert "chore: remove build-command from release action (#50)"

---

buf.gen.yaml
proto/project/v1.proto
schema/observation/v5.json
schema/preset/v2.json
scripts/generate.js
scripts/lib/generate-encode-decode.js
scripts/lib/generate-proto-types.js
scripts/lib/utils.js
src/constants.ts
src/decode.ts
src/encode.ts
src/lib/decode-conversions.ts
src/lib/encode-converstions.ts
src/lib/utils.ts
src/types.ts

`Role`, `Device`, `CoreOwnership` to be tackled in follow-up PR once those schemas are finalized.

feat: type-safe encode function [3/6]

---

package-lock.json
package.json
proto/common/v1.proto
schema/common/v1.json
schema/observation/v5.json
scripts/lib/generate-jsonschema-ts.js
scripts/lib/generate-validations.js
scripts/lib/read-json-schema.js
src/decode.ts
src/encode.ts
src/lib/decode-conversions.ts
src/lib/encode-converstions.ts
src/types.ts
src/validate.ts

Following discussion with @achou11:
- Rename `id` -> `docId`
- Rename `version` -> `versionId`
- Export types for "values", e.g. without common props. These are the types for update/create actions.
- Name "value" types as `${schemaName}Value`
- Rename union of all Mapeo types as `MapeoDoc`

fix: Change prop names and type names [5/6]

---

package-lock.json
package.json
scripts/generate.js
scripts/lib/generate-jsonschema-exports.js
src/index.ts
src/types.ts

Export JSONSchema data. Used by mock data generators, and by Mapeo Core for generating SQL schemas.
- `docSchemas`: Full schemas with merged common properties
- `valueSchemas`: Schemas without the common properties
- `dereferencedDocSchemas`: `docSchemas` with any references resolved and inlined (e.g. `"$ref"` properties replaced with JSON Schema objects)

feat: Export JSONSchema [7/6]

---

schema/observation/v5.json
src/lib/decode-conversions.ts

All top-level properties that are objects or arrays should be required (default to `{}` and `[]`)

fix: observation.metadata should be required.

---

schema/coreOwnership/v1.json
schema/device/v1.json
schema/field/v2.json
schema/observation/v5.json
schema/preset/v2.json
schema/project/v1.json
schema/project/v2.json
schema/role/v1.json
scripts/lib/read-json-schema.js

We had been using `enum` to define the `schemaName` property, however this was proving challenging to work with in the Mapeo Core code - it's easier if we use the `const` keyword, which is more appropriate for this (although they essentially do the same thing).

fix: change schemaName from enum to const

---

proto/coreOwnership/v1.proto
proto/device/v1.proto
proto/role/v1.proto
schema/coreOwnership/v1.json
schema/device/v1.json
schema/role/v1.json

This PR adds missing fields to authStore Schemas and protobufs. 
Things that can be revised:
* some fields name *Id that are typed as `string` on the protobuf could be of type `bytes`.
* `capabilityType` is a `string` but can be an `enum`. Looking at [this code](https://github.com/digidem/mapeo-core-next/blob/main/lib/authstore/authtypes.js) I don't know this should be the name of the role (`projectCreator | coordinator | member | non-member`) or the capabilities (`read | write | manage:devices`).
This should close PR #44

feat: add missing fields to authStore schemas/protos

---

package-lock.json
proto/coreOwnership/v1.proto
proto/device/v1.proto
proto/role/v1.proto
schema/coreOwnership/v1.json
schema/device/v1.json
schema/role/v1.json
src/decode.ts
src/encode.ts
src/lib/decode-conversions.ts
src/lib/encode-converstions.ts
src/types.ts

Things to consider:
* what fields are required? 
* Role: every field
* Device: every field
* coreOwnership: every field
* Device: actions are strings. When we know possible actions, it should be an enum.
* action name delimiters:
protobuf doesn't allow colons (':') on identifiers, so to avoid type problems I basically replaced that delimiter with underscore ('_'). So in schemas `role:set` becomes `role_set`. Another separator could be chosen, or a convertion function (convertAction) could be written; I've tried but failed with that

Conversion functions for authStore types

---

proto/project/v1.proto
proto/project/v2.proto
schema/project/v1.json
schema/project/v2.json
src/lib/decode-conversions.ts
src/lib/encode-converstions.ts

Added `defaultPresets` as an object with `point (string[])` and `area (string[])`.
Since project has two versions for testing foward compatibility I added the field to both of them, but it maybe a good choice to only add it to the newest (v2) so to test foward compatibility on conversion functions (maybe outside of the scope of this tickets). I don't know if having a check for `schemaVersion` on the `decode-conversions.ts/convertProject` function would suffice (it seems like it...)

feat: add defaultPresets to Project doc

---

scripts/lib/generate-jsonschema-exports.js

fix: ensure docSchemas only contains non-dereferenced schemas

---

.github/workflows/release.yml

The optic release action settings were not supposed to be notifying linked issues when publishing a new release to npm, but that wasn't working. The notifications are just introducing a lot of noise right now, so going to turn them off.

fix: don't notify linked issues on npm publish

---

scripts/generate.js
scripts/lib/validate-json-schema.js
test/validate-json-schema.test.js

chore: validate schemas to ensure no top-level null

---

proto/coreOwnership/v1.proto
schema/coreOwnership/v1.json
src/decode.ts
src/encode.ts
src/lib/decode-conversions.ts
src/lib/encode-converstions.ts
src/types.ts
test/fixtures/good-docs-completed.js
test/fixtures/good-docs-minimal.js
test/index.js

Fixes Add `CoreOwnership` schema to `@mapeo/schema` #125
For more details see https://github.com/digidem/mapeo-core-next/issues/175
Stacked on https://github.com/digidem/mapeo-schema/pull/128

feat: Updated core ownership records

---

proto/project/v1.proto
proto/project/v2.proto
schema/project/v1.json
schema/project/v2.json
src/lib/decode-conversions.ts
src/lib/encode-converstions.ts
test/fixtures/good-docs-minimal.js

This removes `name` and `defaultPresets` from the required array of the project jsonschemas.
There's one type error that I've ts-ignored that I'm not sure how to deal with. See the comment below.

make project schema properties optional

---

proto/projectSettings/v1.proto
proto/projectSettings/v2.proto
schema/projectSettings/v1.json
schema/projectSettings/v2.json
src/decode.ts
src/encode.ts
src/lib/decode-conversions.ts
src/lib/encode-converstions.ts
src/types.ts
test/fixtures/good-docs-completed.js
test/fixtures/good-docs-minimal.js

Fixes #114 
Chose `projectSettings` since it seems the most gramatically correct. Shouldn't need to worry about the plural, because we're not pluralizing table names, partly for this reason.

feat: rename project -> projectSettings

---

src/index.ts

This type is not exposed in the public API, but it is needed
for internal use in @mapeo/core (checking signatures)

fix: export MapeoDocInternal type

---

src/index.ts
test/index.js

This adds some tests for encoding the headers of a `MapeoDoc`.
Additionally I've added an export for `encodingBlockPrefix` only to be accessible from the unit test.
This should close #123

feat: header tests

---

proto/observation/v5.proto
schema/observation/v5.json
src/lib/decode-conversions.ts
src/lib/encode-converstions.ts
test/fixtures/cached.js
test/fixtures/good-docs-completed.js

A change to the observation schema to support digidem/mapeo-core-next#220.

add hash in attachments to observation schema

---

proto/observation/v5.proto
schema/observation/v5.json
src/lib/decode-conversions.ts
src/lib/encode-conversions.ts
test/fixtures/cached.js
test/fixtures/good-docs-completed.js

Towards https://github.com/digidem/mapeo-core-next/issues/272
My understanding from the issue is that we want to rename this, but not entirely sure 😄

chore!: rename Attachment.driveId to Attachment.driveDiscoveryId

---

schema/deviceInfo/v1.json

Updates the following:
- Updates `$id` field to include full name e.g. `deviceInfo`, not `device`
- Updates `title` field to use pascal casing like other multi-worded schema defs we have

fix: address naming inconsitencies with the DeviceInfo json schema definition

---

scripts/lib/parse-config.js

This is just a performance optimization for the Mapeo indexer so that it
avoids trying to parse files that are not Mapeo Docs. For example, a
hypercore might have PNG files written to it, which is prefixed by '89
50 4E 47 0D 0A 1A 0A'. If we used this as a dataTypeId then the indexer
would think any PNGs in the core are a Mapeo datatype and try to parse
them. It would fail and just be ignored, but trying to parse would have
a performance cost.
This is a check in the build script that will throw an error if a new
dataType is added that matches one of the known file signature prefixes.
In some cases we don't check against the whole file signature - we just
avoid starting data type IDs with byte(s) that are common in file
signatures.

chore: avoid known file signatures in datatypeId

---

proto/role/v1.proto
schema/role/v1.json

Fairly minor fix - fromIndex should be a positive integer, not just any number

fix: role.fromIndex should be +ve integer

---

src/decode.ts
src/encode.ts
src/lib/decode-conversions.ts
src/lib/encode-conversions.ts
src/lib/utils.ts
test/lib/utils.js

chore: use helper for exhaustiveness checks

---

package-lock.json
package.json
test/index.test.js
test/lib/utils.test.js
test/validate-json-schema.test.js

This was a pretty mechanical change. To do this, I:
* Uninstalled `tap` and replaced it with `node --test`
* Manually rewrote assertions to use `node:assert`
See [multi-core-indexer#39] and [mapeo-sqlite-indexer#27] for similar patches on other repos.
[multi-core-indexer#39]: https://github.com/digidem/multi-core-indexer/pull/39
[mapeo-sqlite-indexer#27]: https://github.com/digidem/mapeo-sqlite-indexer/pull/27

chore: replace Tape with Node's built-in test runner

---

src/index.ts
src/lib/utils.ts
src/validate.ts
test/index.test.js

Exposes validation errors as an array on the `validate()` function, like Ajv does.
Also adds an export of the `valueOf` utility, which can replace the version used in mapeo-core-next.

feat: Expose validation errors

---

buf.gen.yaml
proto/track/v1.proto
schema/track/v1.json
src/decode.ts
src/encode.ts
src/lib/decode-conversions.ts
src/lib/encode-conversions.ts
src/types.ts
test/fixtures/good-docs-completed.js
test/fixtures/good-docs-minimal.js

Add a new `track` schema type.
This was more work than I would have hoped because I wanted to keep timestamps as integers for track locations (as opposed to converting them to ISO date strings), which required lots of backwards compat work. This was maybe a bad idea. But maybe we should switch to timestamps instead of date strings throughout, or switch to `Date` (which would require custom revivers for serializing as JSON over IPC).
Currently this is storing all data captured during track recording, apart from `altitude accuracy`, which seems unnecssary.
To display a track we only really need the latitude and longitude of each position along a track, but at the very least the timestamp is useful too, and the speed, altitude, accuracy and heading could be useful in the future. Each value …

feat: Add track schema type

---

proto/observation/v1.proto
schema/observation/v1.json
src/lib/decode-conversions.ts
src/lib/encode-conversions.ts
test/fixtures/bad-docs.js
test/fixtures/good-docs-completed.js
test/fixtures/good-docs-minimal.js

This isn't necessary for now, so we can remove it.
`refs` is still present for `Track`s.
Tested this with automated tests and by integrating it into `@mapeo/core` with a temporary build of this module.
Closes #193.

chore!: remove `refs` property from schemas

---

proto/deviceInfo/v1.proto
proto/field/v1.proto
proto/icon/v1.proto
proto/observation/v1.proto
proto/preset/v1.proto
proto/track/v1.proto
schema/deviceInfo/v1.json
schema/field/v1.json
schema/icon/v1.json
schema/observation/v1.json
schema/track/v1.json
src/lib/decode-conversions.ts

should close #171. 
Instead of having a field "unspecified" for enums, I had to be deliberate (so `${enum_name_in_snake_case}_unspecified`) since protobufs don't allow enums to have fields with the same name

add unspecified field to enums

---

proto/projectSettings/v1.proto
schema/projectSettings/v1.json
src/lib/decode-conversions.ts
test/fixtures/cached.js
test/fixtures/good-docs-completed.js
test/fixtures/good-docs-minimal.js

This should move forward exposing config metadata to the frontend. 
Part of https://github.com/digidem/comapeo-mobile/issues/527

feat: add `configMetadata` to `projectSettings`

---

schema/preset/v1.json
src/lib/decode-conversions.ts
src/lib/encode-conversions.ts

On https://github.com/digidem/mapeo-schema/pull/199/ we forgot to add `iconRef` to the `Preset` JSONSchema. This wasn't caught since `iconRef` is optional on the protobuf definition. Despite that I thought it would be caught since we don't allow additional properties on any JSONSchema.

chore: add iconRef to preset schema

---

proto/translation/v1.proto
schema/translation/v1.json
src/lib/decode-conversions.ts
src/lib/encode-conversions.ts
test/fixtures/good-docs-completed.js
test/fixtures/good-docs-minimal.js

when adding `docRef` to translation I initially put the `type` of ref inside `docRef`. Integrating with mapeo-core-next I realized that some stuff were more complicated than needed and that the code (and types) could be simpler if we removed `type` from `docRef` and added as its own feld (now called `refType`)

chore: move type out of `docRef` and call it `docRefType`

---

proto/observation/v1.proto
schema/observation/v1.json
src/lib/decode-conversions.ts
src/lib/encode-conversions.ts
test/fixtures/good-docs-completed.js
test/fixtures/good-docs-minimal.js

should close #205. I put it as required on JSONSchema and non-optional on the proto definition

feat: add `presetRef` to observation

---

package.json

`npm test` now runs `prettier --check .` to ensure all of our files are formatted correctly.

chore: check code formatting on test

---

package-lock.json
package.json

Based on https://pkg-size.dev/@mapeo%2Fschema@3.0.0-next.19, I think including [`typedoc` is including a pinned version of typescript as a direct/peer dep](https://github.com/TypeStrong/typedoc/blob/v0.24.8/package.json), which causes installation for any module consuming @mapeo/schema to be incredibly slow (basically it's installing TS v5.1 alongside whatever TS version you've specified for yourself at the top level e.g. in an application project).
My understanding is that typedoc and any relevant plugins are only used at build-time, so it would make more sense for these to be defined as dev dependencies

chore: move typedoc-related deps to dev deps

---

package-lock.json
package.json

Summary of changes:
- `@json-schema-tools/dereferencer`: upgrades to `^1.6.3` and move to dev deps
- `ajv`: move to dev deps
- `ajv-formats`: removed
- `glob`: update to v11 (removes node support for < 20) and move to dev deps

chore: clean up deps

---

package.json

This change should have no user impact.
`npm run format` will run Prettier on all files.

chore: add auto-format npm script

---

scripts/lib/generate-config.js
scripts/lib/generate-proto-types.js
src/decode.ts
src/lib/utils.ts
test/index.test.js
test/lib/utils.test.js
tsconfig.json

We can now decode future schema versions without throwing. For example, if some future version encodes `Observation_2`, we can decode it as an `Observation_1`.
Closes #168.

feat: decode future schema versions without throwing

---

.github/workflows/release.yml

previously we were using `npm install`

chore: use npm ci on release

---

schema/field/v1.json
schema/icon/v1.json
schema/observation/v1.json
schema/preset/v1.json

should close #202 
all version of JSONSchemas (field `$id` on the schema file), should be the same as the filename version, and they should all be version 1

chore: version all schemas to v1

---

package-lock.json
package.json

This updates `type-fest` to v4.26.0, the latest version.

chore: update type-fest dependency to latest version

---

proto/observation/v1.proto
schema/observation/v1.json

This is a partial revert of 4ce47f09ba980fbc70a978b1afc399e22313382e.
It turns out that observations can, in edge cases, lack a location. This makes its `lat` and `lon` fields optional.

feat!: make observation location optional

---

proto/deviceInfo/v1.proto
schema/deviceInfo/v1.json

This adds a new device type, `selfHostedServer`. This is part of our self-hosted cloud work.
Closes #187.

feat: add "self hosted server" device type

---

proto/observation/v1.proto
schema/observation/v1.json

This object should match [how we collect the data on the frontend][0].
Closes #231.
[0]: https://docs.expo.dev/versions/latest/sdk/location/#locationobjectcoords

fix!: make Observation metadata coords fields optional

---

proto/observation/v1.proto
schema/observation/v1.json

This object matches [Expo's `LocationObjectCoords` type][0], so we should take all of its fields. We were missing `altitudeAccuracy`.
[0]: https://docs.expo.dev/versions/latest/sdk/location/#locationobjectcoords

feat: add `altitudeAccuracy` to observation metadata

---

test/fixtures/good-docs-completed.js
test/fixtures/good-docs-minimal.js

1f239c9f77a8db8afba92d77bdf7c34cfa730753 replaced `MapeoDocInternal` with `MapeoDocDecode` and `MapeoDocEncode`. This updates our fixtures to use those, because it was previously (incorrectly) using `MapeoDocInternal`.
`git grep MapeoDocInternal` returns no results after this change.

test: use correct type for fixtures

---

schema/field/v1.json
src/lib/encode-conversions.ts

This is a partial revert of 4ce47f09ba980fbc70a978b1afc399e22313382e.
`universal` should be non-optional in the protobuf (for serialization) but optional in the schema. This fixes that.

chore!: make Field's `universal` property optional in schema

---

src/lib/decode-conversions.ts

Followup for 4dc97dce071671291874e68da02702b94af3a8a1.

fix: don't require iconRef for presets

---

src/encode.ts
src/lib/encode-conversions.ts

This change should have no user impact.
This removes a few unused imports from a few files.
I think this is a useful change on its own, but it should make [an upcoming change][1] easier too.
[1]: https://github.com/digidem/mapeo-schema/pull/243

chore: remove unused imports

---

scripts/lib/generate-jsonschema-exports.js
scripts/lib/generate-jsonschema-ts.js
src/decode.ts
src/encode.ts
src/typedefs/compact-encoding.d.ts
test/fixtures/good-docs-completed.js
test/index.test.js

_Depends on #244._
This change should have no user impact.
There's almost always something better than `// @ts-ignore` and `// @ts-expect-error`. They can be problematic because they're very broad, and typically broader than we want. For details, see ["At least 7 reasons to avoid @ts-expect-error and @ts-ignore"][0].
This removes all of them in favor of more targeted solutions. (Or, in one case, just removes it and everything was fine!)
I think this is a useful change on its own, but it should make [an upcoming change][1] easier too.
[0]: https://shane-o.dev/articles/any-or-expect
[1]: https://github.com/digidem/mapeo-schema/pull/243

chore: remove `ts-ignore` and `ts-expect-error`

---

buf.gen.yaml
proto/observation/v1.proto
schema/observation/v1.json
src/lib/decode-conversions.ts
src/lib/encode-conversions.ts
test/fixtures/bad-docs.js
test/index.test.js

boy protobuf and typescript are tricky beasts...
So there were a few edge-cases around the way we type, encode and decode observation position metadata.
We were using `fromPartial` for encoding metadata, which assigns defaults for missing props, which meant that decoding would pass type checks, but defaults would be assigned to the missing props, in this case `longitude` and `latitude`, which is a "null island" bug.
This PR makes a few changes:
- `manualLocation` is now optional in protobuf - the distinction between when this is `undefined` (when there is no location for the observation) and when it is boolean (when there is a location) is important.
- `gpsAvailable`, `networkAvailable`, `passiveAvailable` props of `metadata.positionProvider` are now optional on the protobuf, to …

fix: observation metadata types

---

test/index.test.js

Previously, we intended to test the validation of bad docs but weren't doing so correctly. This fixes that.

test: properly test more `validate` errors

---

package-lock.json
package.json
src/decode.ts
src/encode.ts

This is a types-only change.
[`@types/compact-encoding`][0] was recently published. Let's use that instead of ignoring the type.
[0]: https://www.npmjs.com/package/@types/compact-encoding

chore: use upstream types for `compact-encoding`

---

proto/projectSettings/v1.proto
schema/projectSettings/v1.json
test/fixtures/good-docs-completed.js
test/fixtures/good-docs-minimal.js

[Gregor rightly pointed out that this value is synced][0]. Given that this value is currently unused on the frontend, we should remove it.
[0]: https://github.com/digidem/comapeo-core/issues/751#issuecomment-2337594457

fix!: remove `isInitialProject` from project settings

---

package-lock.json
package.json
scripts/lib/generate-validations.js

JavaScript module inconsistency strikes again.
In some cases, Ajv will inject `require` calls into generated code even if you ask it to generate ESM. [This is a bug][0].
For example, here's something it adds if you use [the string `minLength` or `maxLength` properties][1]:
```javascript
// ...
const func2 = require("ajv/dist/runtime/ucs2length").default;
// ...
```
That won't work in an ESM environment.
As a workaround, I inject the following into our generated code:
```javascript
import { createRequire } from 'node:module';
const require = createRequire(import.meta.url);
```
This, along with moving `ajv` to production dependencies, should work around this issue until the bug is fixed.
*This isn't a problem today*, but will immediately become a problem if we start using one of those …

chore: work around Ajv module bug in generated code

---

proto/coreOwnership/v1.proto
schema/coreOwnership/v1.json
src/lib/decode-conversions.ts
src/lib/utils.ts
test/fixtures/bad-docs.js

This change:
- Marks all `CoreOwnership` core IDs `required` in the proto
- Gives each core ID a minimum length in the schema
- Validates this length when decoding
- Adds a test for the above

chore: make CoreOwnership core IDs required

---

scripts/lib/generate-validations.js
src/lib/ucs2length.ts

This is a different approach to the fix in #256 because that was not playing nicely with Rollup bundler.
This PR vendors the `ucs2length` code from the AJV runtime (this code checks a string's length), and modifies the generated validation code to use the vendored version.

fix: fix AJV runtime validation code ESM compatibility

---

CONTRIBUTING.md
README.md
package.json
src/lib/utils.ts

feat!: rename to `@comapeo/schema`

---

package-lock.json
package.json

Now that we vendor ucs2length, ajv is not needed at runtime

chore: make ajv a dev dep

---

package-lock.json
package.json

comapeo-geometry had a bug where it didn't had a `type` field on its schema. This is used in a check in comapeo-core, so we need that udpate on comapeo-schema

chore: update comapeo-geometry to 1.0.2

---

.github/workflows/release.yml

This is the equivalent to [this change][0]. To quote that commit:
> The optic release option `sync-semver-tags` creates additional tags (`v{MAJOR}`, `v{MAJOR}.{MINOR}`) which are updated on each release.  This currently does not work because this tag push happens with the permissions of the default github actions token, which does not have rule bypass permissions. It's a "soft fail" (the release still gets made), and the full version tag comes from the release creation, which is done by the optic release app, which is included in our ruleset bypass list.
>
> We don't need these tags, and they are not working, so this [commit] turns this option off.
I plan to YOLO-merge this if CI passes.
[0]: https://github.com/digidem/comapeo-core/commit/d3dc9d852d75ba376257ebc94282ebaaf61cf617

chore: don't sync semver tags for releases

---

proto/observation/v1.proto
schema/observation/v1.json
src/lib/decode-conversions.ts
src/lib/encode-conversions.ts

This adds a new field, `migrationMetadata`, which has two sub-fields:
- `originalDocument`: the original observation, in case we ever need it
- `hypercore`: metadata about the observation in the old Hypercore
I considered adding this to the `Common` schema, but I don't think it makes sense there because we won't necessarily be migrating all types, like `CoreOwnership`.

feat: add migration metadata to observation schema

---

proto/observation/v1.proto
schema/observation/v1.json
src/lib/decode-conversions.ts
src/lib/encode-conversions.ts

These changes had bugs and should not be released. Strictly this is a
breaking change, but we have not created a release with updated
comapeo-schema yet.

chore: revert migrated observation metadata schema changes

---

proto/projectSettings/v1.proto
schema/projectSettings/v1.json
src/lib/encode-conversions.ts
test/fixtures/bad-docs.js
test/fixtures/good-docs-completed.js

Addresses https://github.com/digidem/comapeo-core/issues/1014
- `projectDescription` is an **optional** string
- `projectColor` is an **optional** string, where the string must be hex formatted (e.g. `#000000`). we could make this a required field but I believe that would require backfilling a default value for documents from older schema versions. I feel a bit uneasy about the schema being prescriptive for something like that, which is usually app-specific.

feat: add project color and description fields to project settings

---

.github/workflows/lockfile.yml

Slightly adapted from https://github.com/digidem/comapeo-mobile/blob/387ab482ee4e76d5c6f4a68cb47f81863c603945/.github/workflows/lockfile.yml

chore(ci): add workflow for lockfile checks

---

proto/observation/v1.proto
schema/observation/v1.json

Related to https://github.com/digidem/comapeo-mobile/issues/1043, where we want to display the `FNumber` field from the EXIF data

fix: add FNumber to photo exif type

---

proto/observation/v1.proto
schema/observation/v1.json
src/lib/decode-conversions.ts
src/lib/encode-conversions.ts
test/fixtures/good-docs-completed.js

Closes #298 
Adds an ~optional~ boolean field to an attachment called `external`, which indicates whether the associated media for an attachment was created outside of CoMapeo e.g. manually uploading an image/video/audio file that was created from another device, application that isn't CoMapeo, etc.
The user-facing intent of this is to determine if the attachment is "validated" by CoMapeo.

feat!: add "external" field to attachment definition
